alias:
  - "o:openai/o3"
  - "o-mini:openai/o4-mini"
  - "gemini:vertex_ai/gemini-2.5-pro-preview-05-06"
  - "flash:vertex_ai/gemini-2.5-flash-preview-05-20"
  - "gpt:openai/gpt-4.1"
  - "gpt-mini:openai/gpt-4.1-mini"
  - "sonnet:claude-sonnet-4-20250514"
  - "opus:claude-opus-4-20250514"

## Default model
model: gemini
weak-model: flash

auto-commits: false

cache-prompts: true

# Disabled due to hitting too many open file limits
watch-files: false

dark-mode: true

show-release-notes: false
analytics-disable: true
