alias:
  - "o:openai/o3"
  - "o-mini:openai/o4-mini"
  - "gemini:vertex_ai/gemini-2.5-pro-preview-03-25"
  - "flash:vertex_ai/gemini-2.5-flash-preview-04-17"
  - "gpt:openai/gpt-4.1"
  - "gpt-mini:openai/gpt-4.1-mini"

## Default model
model: gemini
#model: sonnet

auto-commits: false

cache-prompts: true

# Disabled due to hitting too many open file limits
watch-files: false

#dark-mode: true

show-release-notes: false
analytics-disable: true
