# Always added to the context
#read:
#  - CONVENTIONS.md

## Default model for main chat
model: vertex_ai/gemini-2.5-pro-preview-03-25

#model: sonnet
#model: o3-mini
#model: o1
#model: gpt-4o

# Gemini gemini/gemini-2.0-flash-exp
#model: flash

auto-commits: false

cache-prompts: true

# Disabled due to hitting too many open file limits
watch-files: false

#dark-mode: true

show-release-notes: false
analytics-disable: true
